
[ 'Group_ID', '加工阶段', '过账日期', '委外工单号', '库存地点', '物料', 'CHIPONELOT', 'FOUNDRYLOT', 'Wafer id', '辅料批次', 
  'BIN别', 'Runcard', '工厂工单号', '移动类型', '数量(片数）', '数量（颗数）', 'SCRAP数量', 'DATECODE', '入库日期', '生产日期',
  '结批标识', 'Turn key标识', '说明/备注', 'CP1程序', 'CP2程序', 'CP3程序', 'CP4程序', 'CP5程序', 'CP6程序', 'CP7程序', 
  '标签格式', '条数', 'FT1程序', 'FT2程序', 'FT3程序', 'FT4程序', 'FT5程序', '凭证日期','工厂','批次','特殊库存状态',
  '供应商','交易单位','平行数量','平行单位','项目编号','成本中心','WBS元素','CompanyCode','OSATRuncard','LotNumber',
  'WaferLotNO','WwaferId','WaferQty','ChipQty','DateCode','FreightCarrier','ShipToName',
  'ShipToAddress','ShipDate','SShip To Address',
  '接收工厂代码','接收方供应商简称','接收库存状态','接收物料编码','接收批次号','调拨通知单号','调拨通知单行',
  ]




DATA = [
  {"excel_header" : "Group_ID","its_header": "uf_group_id" ,"is_required" : "Y"},
  {"excel_header" : "加工阶段","its_header"  : "uf_process_stage"  ,"is_required" : "N"}, 
  {"excel_header" : "过账日期","its_header"  : "uf_posting_date" },
  {"excel_header" : "委外工单号","its_header"  : "uf_po_sn" },
  {"excel_header" : "库存地点","its_header"  : "uf_stor_loc_code" },
  {"excel_header" : "物料","its_header"  : "uf_mat_code" },
  {"excel_header" : "CHIPONELOT","its_header"  : "uf_lot_no" },
  {"excel_header" : "FOUNDRYLOT","its_header"  : "ZT04" }, 
  {"excel_header" : "Wafer id","its_header"  : "uf_wafer_id" }, 
  {"excel_header" : "行项目号","its_header"  : "uf_line_id" }, 
  {"excel_header" : "辅料批次","its_header"  : "uf_auxiliary_material_batch_sn" },
  {"excel_header" : "BIN别","its_header"  : "bin" }, 
  {"excel_header" : "Runcard","its_header"  : "uf_runcard" }, 
  {"excel_header" : "工厂工单号","its_header"  : "uf_plant_code" },
  {"excel_header": "数量（颗数）", "its_header": "uf_parallel_qty"},
  {"excel_header" : "移动类型","its_header"  : "uf_movement_type" },
  {"excel_header" : "数量(片数）","its_header"  : "uf_transaction_qty" },
  {"excel_header" : "SCRAP数量","its_header"  : "uf_SCRAP_Quantity" },
  {"excel_header" : "DATECODE","its_header"  : "uf_date_code" }, 
  {"excel_header" : "事务代码","its_header"  : "uf_transaction" }, 
  {"excel_header" : "入库日期","its_header"  : "uf_storage_date" },
  {"excel_header" : "生产日期","its_header"  : "uf_production_date" },
  {"excel_header" : "结批标识","its_header"  : "uf_batch_closure_flag" },
  {"excel_header" : "Turn key标识","its_header"  : "uf_turn_key" },
  {"excel_header" : "说明/备注","its_header"  : "uf_extended_batch_attributes1" },
  {"excel_header" : "CP程序","its_header"  : "uf_ZT05" },
  {"excel_header" : "CP1程序","its_header"  : "uf_ZT05" },
  {"excel_header" : "CP2程序","its_header"  : "uf_ZT20" },
  {"excel_header" : "CP3程序","its_header"  : "uf_ZT21" },
  {"excel_header" : "CP4程序","its_header"  : "uf_ZT35" },
  {"excel_header" : "CP5程序","its_header"  : "uf_ZT36" },
  {"excel_header" : "CP6程序","its_header"  : "uf_ZT37" },
  {"excel_header" : "CP7程序","its_header"  : "uf_ZT38" },
  {"excel_header" : "标签格式","its_header"  : "uf_ZT09" },
  {"excel_header" : "条数","its_header"  : "uf_ZT17" },
  {"excel_header" : "FT1程序","its_header"  : "uf_ZT06" },
  {"excel_header" : "FT2程序","its_header"  : "uf_ZT48" },
  {"excel_header" : "FT3程序","its_header"  : "uf_ZT49" },
  {"excel_header" : "FT4程序","its_header"  : "uf_ZT50" },
  {"excel_header" : "FT5程序","its_header"  : "uf_ZT51" },
  {"excel_header": "出货单号", "its_header": "uf_ito_sn"},
  {"excel_header": "出货单行号", "its_header": "uf_ito_items"},
  {"excel_header": "发出仓位代码", "its_header": "uf_stor_loc_code"},
  {"excel_header": "发出仓位名称", "its_header": "stor_loc_desc"},
  {"excel_header": "接收仓位代码", "its_header": "uf_rcv_stor_loc_code"},
  {"excel_header": "接收仓位名称", "its_header": "uf_rcv_stor_loc_desc"},
  {"excel_header": "二级订单号", "its_header": "uf_secondary_order"},
  {"excel_header": "客户简称", "its_header": "customer_short_name"},
  {"excel_header": "客户PO", "its_header": "uf_customer_po_no"},
  {"excel_header": "箱号", "its_header": "uf_box_no"},
  {"excel_header": "工单号", "its_header": "uf_wo_sn"},
  {"excel_header": "bin别", "its_header": "uf_bin"},
  {"excel_header": "Ship Date", "its_header": "uf_posting_date"},
  {"excel_header": "EPN", "its_header": "uf_epn"},
  {"excel_header": "IPN", "its_header": "uf_ipn"},
  {"excel_header": "封装形式", "its_header": "uf_ZT08"},
  {"excel_header": "OSAT Runcard", "its_header": "uf_runcard"},
  {"excel_header": "Lot Number", "its_header": "uf_lot_no"},
  {"excel_header": "Wafer Lot No", "its_header": "uf_wafer_lot_no"},
  {"excel_header": "Wafer id", "its_header": "uf_wafer_id"},
  {"excel_header": "Wafer Qty", "its_header": "uf_wafer_qty"},
  {"excel_header": "Chip Qty", "its_header": "uf_chip_qty"},
  {"excel_header": "Date Code", "its_header": "uf_ZT18"},
  {"excel_header": "条数", "its_header": "uf_ZT17"},
  {"excel_header": "封装厂", "its_header": "uf_ZT14"},
  {"excel_header": "测试厂", "its_header": "uf_ZT15"},
  {"excel_header": "实际物流单号", "its_header": "uf_actual_logistics_sn"},
  {"excel_header": "虚拟物流单号", "its_header": "uf_virtual_logistics_sn"},
  {"excel_header": "Freight Carrier", "its_header": "uf_freight_carrier"},
  {"excel_header": "Ship To Name", "its_header": "uf_ship_to_name"},
  {"excel_header": "Ship To Address", "its_header": "uf_ship_to_address"},
  {"excel_header": "联系人", "its_header": "uf_contact_person"},
  {"excel_header": "测试程序", "its_header": "uf_test_program"},
  {"excel_header": "CPN", "its_header": "uf_cpn"},
  {"excel_header": "毛重", "its_header": "uf_gross_weight"},
  {"excel_header": "净重", "its_header": "uf_net_weight"},
  {"excel_header": "尺寸", "its_header": "uf_size"},
  {"excel_header": "产地", "its_header": "uf_origin_place"},
  {"excel_header": "Company Code", "its_header": "uf_company_code"},
  {"excel_header": "采购订单号", "its_header": "uf_po_sn"},
  {"excel_header": "行项目", "its_header": "uf_po_item"},
  {"excel_header": "收货库存地点", "its_header": "uf_mat_code"},
  {"excel_header": "物料编码", "its_header": "uf_mat_code"},
  {"excel_header": "数量", "its_header": "count"},
  {"excel_header": "供应商Lot", "its_header": "count"},
  {"excel_header": "发票号", "its_header": "count"},
  {"excel_header": "批次号", "its_header": "uf_batch_sn"},
  {"excel_header": "贸易类型", "its_header": "count"},
  {"excel_header": "单价(不含税)", "its_header": "count"},
  {"excel_header": "电镀日期(YYYYMMNN)", "its_header": "uf_electroplating_date"},
  {"excel_header": "业务类别", "its_header": "bs_category"},
  {"excel_header": "汇总号", "its_header": "summary_unique_number"},
  {"excel_header": "物料凭证行唯一标识", "its_header": "line_id"},
  {"excel_header": "工厂代码", "its_header": "plant_code"},
  {"excel_header": "发出方供应商简称", "its_header": "vendor_short_name"},
  {"excel_header": "库存状态", "its_header": "inventory_status"},
  {"excel_header": "交易数量", "its_header": "transaction_qty"},
  {"excel_header": "运单号", "its_header": "express_delivery"},
  {"excel_header": "接收库存地点编码", "its_header": "receive_storage_location_code"},
  {"excel_header": "生产周", "its_header": "uf_ZT18"},
  {"excel_header": "制造日期", "its_header": "production_date"},
  {"excel_header": "Invoice_Date", "its_header": "invoice_date"},
  {"excel_header": "Invoice_Number", "its_header": "invoice_number"},
  {"excel_header": "Customer_PO", "its_header": "customer_po"},
  {"excel_header": "Customer_Product_ID", "its_header": "customer_product_id"},
  {"excel_header": "FAB_Product_ID", "its_header": "fab_product_id"},
  {"excel_header": "Lot_No", "its_header": "lot_no"},
  {"excel_header": "Ship_Qty", "its_header": "ship_qty"},
  {"excel_header": "UNIT_PRICE", "its_header": "unit_price"},
  {"excel_header": "Amount", "its_header": "amount"},
  {"excel_header": "Wafer_ID", "its_header": "wafer_id"},
  {"excel_header": "Forwarder", "its_header": "forwarder"},
  {"excel_header": "HAWB", "its_header": "hawb"},
  {"excel_header": "Ship_To", "its_header": "ship_to"},
  {"excel_header": "Cust_code", "its_header": "cust_code"},
  {"excel_header": "Lot_Owner", "its_header": "lot_owner"},
  {"excel_header": "Status", "its_header": "status"},
  {"excel_header": "GROSS_DIE", "its_header": "gross_die"},
  {"excel_header" : "凭证日期","its_header": "uf_document_date"},
  {"excel_header" : "工厂","its_header": "uf_plant_code"},
  {"excel_header" : "批次","its_header": "uf_batch_sn"},
  {"excel_header" : "特殊库存状态","its_header": "uf_special_inventory_status1"},
  {"excel_header" : "供应商","its_header": "uf_vendor_code"},
  {"excel_header" : "交易单位","its_header": "uf_transaction_uom"},
  {"excel_header" : "平行数量","its_header": "uf_parallel_qty"},
  {"excel_header" : "平行单位","its_header": "parallel_uom"},
  {"excel_header" : "项目编号","its_header": "uf_project_sn"},
  {"excel_header" : "成本中心","its_header": "uf_cost_center"},
  {"excel_header" : "WBS元素","its_header": "uf_wbs_elements"},
  {"excel_header" : "供应商批次","its_header": "uf_vendor_batch"},
  {"excel_header" : "CompanyCode","its_header": "uf_company_code"},
  {"excel_header" : "OSATRuncard","its_header": "uf_osat_runcard"},
  {"excel_header" : "LotNumber","its_header": "uf_lot_number"},
  {"excel_header" : "WaferLotNO","its_header": "uf_wafer_lot_no"},
  {"excel_header" : "WwaferId","its_header": "uf_wwafer_id"},
  {"excel_header" : "WaferQty","its_header": "uf_wafer_qty"},
  {"excel_header" : "ChipQty","its_header": "uf_chip_qty"},
  {"excel_header" : "DateCode","its_header": "uf_date_code"},
  {"excel_header" : "FreightCarrier","its_header": "uf_freight_carrier"},
  {"excel_header" : "ShipToName","its_header": "uf_ship_to_name"},
  {"excel_header" : "ShipToAddress","its_header": "uf_ship_to_address"},
  {"excel_header" : "ShipDate","its_header": "uf_posting_date"},
  {"excel_header" : "SShip To Address","its_header": "uf_ship_to_address"},
  {"excel_header" : "接收工厂代码","its_header": "uf_receive_plant_code"},
  {"excel_header" : "接收方供应商简称","its_header": "uf_receive_vendor_short_name"},
  {"excel_header" : "接收库存状态","its_header": "uf_receive_inventory_status"},
  {"excel_header" : "接收物料编码","its_header": "uf_receive_mat_code"},
  {"excel_header" : "接收批次号","its_header": "uf_receive_batch_sn"},
  {"excel_header" : "调拨通知单号","its_header": "uf_transfer_notification_sn"},
  {"excel_header" : "调拨通知单行","its_header": "uf_transfer_notification_line"},

]